server:
  port: 8022
spring:
  application:
    name: microservice-consumer-movie-feign-with-hystrix-stream
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    hostname: feign
    preferIpAddress: false
     # 此处，preferIpAddress不设置或者设为false，不能设为true，否则影响turbine的测试。
     # turbine存在的问题：eureka.instance.hostname一致时只能检测到一个节点，会造成turbine数据不完整
ribbon:
  eureka:
    enabled: true
    # 默认为true。如果设置为false，Ribbon将不会从Eureka中获得服务列表，
    #而是使用静态配置的服务列表。静态服务列表可使用：<client>.ribbon.listOfServers来指定。参考：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#spring-cloud-ribbon-without-eureka
feign:
  hystrix:
    enabled: true
    # 最新版本的feign的hystrix默认关闭 1.3以上的netflix
