server:
  port: 8050
spring:
  application:
    name: microservice-config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/a247292980/spring-cloud-microservice-config
          search-paths: config-repo
          username: a247292980
          password: 123456789
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/