server:
  port: 8022
spring:
  application:
    name: microservice-consumer-movie-feign-with-hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true
     # 默认为true。如果设置为false，Ribbon将不会从Eureka中获得服务列表，
     #而是使用静态配置的服务列表。静态服务列表可使用：<client>.ribbon.listOfServers来指定。
     #参考：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#spring-cloud-ribbon-without-eureka
feign:
  hystrix:
    enabled: true
    # 最新版本的feign的hystrix默认关闭 1.3以上的netflix